namespace: apps

nameOverride:

job:
  schedule: "1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1

image:
  pullPolicy: IfNotPresent
  repository: ...
  tag: 0.1.0
  pullSecretName: ghcr

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

env:
  # Contains transparent environment variables
  open:
    LOG_LEVEL: info
  # Stores secret environment variables
  existingSecret:
  existingSecretMappings:
    # Map keys from existing secret to environment variable names
    ENV_VAR_NAME: key-name
