namespace: apps

nameOverride:

schedule: "1 * * * *"

image:
  pullPolicy: IfNotPresent
  repository: 533806089962.dkr.ecr.eu-central-1.amazonaws.com/portfolio-qplix-scraper
  version: 0.1.0

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

env:
  # Contains transparent environment variables
  open:
    LOG_LEVEL: info
  # Stores secret environment variables
  existingSecret:
  existingSecretMappings:
    # Map keys from existing secret to environment variable names
    ENV_VAR_NAME: key-name
