nameOverride:

job:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  terminationGracePeriodSeconds: 30
  restartPolicy: Never
  command: []
  args: []
  env:
    # Contains transparent environment variables
    open:
      LOG_LEVEL: info
    # Stores secret environment variables
    existingSecret:
    existingSecretMappings:
      # Map keys from existing secret to environment variable names
      # ENV_VAR_NAME: key-name

image:
  pullPolicy: IfNotPresent
  repository: ...
  tag: 0.1.0
  pullSecretName: ghcr

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

podSecurityContext:
  enabled: true
  runAsUser: 1001
  fsGroup: 1001
  runAsNonRoot: true

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  allowPrivilegeEscalation: true
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true
