---
{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helpers.fullname" . }}
  labels: {{- include "helpers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector: {{- include "helpers.selectorLabels" . | nindent 4 }}
{{- end }}
