---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "helpers.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: "Helm"
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
    meta.helm.sh/release-name: {{ include "helpers.name" . }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
